import type { Metadata } from 'next';

import AuthProvider from '@/providers/AuthProvider';
import NextUIProvider from '@/providers/NEXTUIProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Pleas ask here',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
