import type { Metadata } from 'next';

import AuthProvider from '@/providers/AuthProvider';
import UIProviders from '@/providers/NEXTUIProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Pleas ask here',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-gray-100 h-full " lang="en">
      <body className="h-full">
        <AuthProvider>
          <UIProviders>{children}</UIProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
