name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0
      - name: Run tests
        run: |
          npm run test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/please-ask-here:latest
      - name: SSH sign and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_SECRET:${{ secrets.AUTH_GITHUB_SECRET }}
            GITHUB_ID:${{ secrets.AUTH_GITHUB_ID }}
            NEXTAUTH_SECRET:${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL:${{ secrets.NEXTAUTH_URL }}
          script: |
            docker stop PSH-containers
            docker remove PSH-containers
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/please-ask-here:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/please-ask-here:latest
            docker run -d --name PSH-containers \
            -e GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }} \
            -e GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/please-ask-here:latest
